### ISSUE TITLE
Get Database tests running

### ISSUE THREAD

**Issue by Odrakir** [toggl/ios#164]
## Description
Database tests as they are right now don't work. You can execute them manually, but Xcode or Bitrise won't find them since they are swift generic classes and those are not compatible with `XCTestCase`

So... that means they have to be refactored some how so they work. Your mission, should you choose to accept it, is exactly that.

## Definition of done
- [ ] Exactly the same tests that can be now manually run are automatically run 
- [ ] Those tests run in Xcode (when hitting command + u) and in Bitrise

**Comment by juanlaube** [comment]
I've found a partial solution:

I tried this with `ClientDatabaseTests` only, but the idea should work for any other test class.
I renamed `ClientDatabaseTests` to `ClientDatabaseTestsCases` and added the following snippet:
```
class ClientDatabaseTests: XCTestCase {

    override func run() {
        super.run()
        print(ClientDatabaseTestsCases.self)
        let suite = XCTestSuite(forTestCaseClass: ClientDatabaseTestsCases.self)
        suite.run()
    }

    func testDummy() {
        XCTAssert(true)
    }
}
```

Unfortunately this only works when `Database.framework` is a dynamic framework, otherwise it fails at runtime with a nasty mangling issue.

**Comment by Odrakir** [comment]
To make it work without the need of making the framework dynamic you can just add this line to `App/Configurations/base/Tests-Base.xcconfig"

```
OTHER_LDFLAGS = -all_load
```

[Reference](https://stackoverflow.com/a/55584095)
